### ISSUE TITLE
pull sample files from databrary

### ISSUE THREAD

**Issue by jukaradayi** [srvk/DiViMe#15]
please replace the sample file for the test with these ones:
https://nyu.databrary.org/volume/390

**Comment by riebling** [comment]
awaiting latest password to access Password/Warlaumont

**Comment by alecristia** [comment]
good question! It should not pull things that require password, it should build only on the public section. 

Changing who's in charge since I know Julien has seen the issues below before, and he'll be able to:
- make sure after the pull is done, the files get organized correctly (since the databrary structure has lots of unnecessary nesting)
- the .eaf and wav files are processed if need be
- IMPORTANT: One thing to beware of is that some section of volume 390 is private. From memory, the sounds are all public, but some of the annotations are private. We should make sure that when this happens, the system does not hallucinate empty (=no speech present) annotations...

**Comment by riebling** [comment]
Maybe I'm misunderstanding, you want ALL the files from Warlamount/ ? I have updated the test.wav with a new snippet from one of these recordings. I forget whether we need to keep test2.wav, or can eliminate it. Suspicious because there is a test2.rttm, which I suspect is an "expected output", but cannot know from which tool it originated.

The new test2.wav has interaction between a father and child.

**Comment by alecristia** [comment]
The context of the initial request is that by doing this, we are publicizing the aclew starter AND providing relevant sample files.

Replies to your Qs:
_I have a copy on my computer of the complete Aclew-Starter, but I still can't download some of the files from Databrary because they remain private (the three CAS eaf files and the three ROW files).
I can put the version I have now, but there are two things:
1 - I'm not sure it is the latest version (the three CAS and three ROW files might have been updated since I got them ?)_
<-- in theory, neither the wav nor the annotations will change ever. However, you should indeed budget for some files not being available, and thus they should NOT be made available in any way. 

_2 - Should I include the files "hard coded", or should I make it in a way that when you clone the DiViMe repository it downloads the files from databrary ? Do you know if the files from the Aclew Starter are going to be updated ?_
Please clone. See the above :)

_Maybe I'm misunderstanding, you want ALL the files from Warlamount/ ? I have updated the test.wav with a new snippet from one of these recordings. I forget whether we need to keep test2.wav, or can eliminate it. Suspicious because there is a test2.rttm, which I suspect is an "expected output", but cannot know from which tool it originated.
The new test.wav has interaction between a father and child.
I need to look through individual tools' documentation to see if/where/which refers to the test audio + expected RTTM._
The idea would be to not rename the ACLEW Starter component, but indeed to have the test tool use them rather than some other test file. Regarding whether they should "all" be there -- it is okay that the test does not rely on files that are not public (ROW and CAS for now, according to Julien).

**Comment by alecristia** [comment]
By the way, this also means in the README we should cite the ACLEW starter data:
Bergelson, E., Warlaumont, A., Cristia, A., Casillas, M., Rosemberg, C., Soderstrom, M., Rowland, C., Durrant, S. & Bunce, J. (2017). Starter-ACLEW. Databrary. Retrieved August 15, 2018 from http://doi.org/10.17910/B7.390.

**Comment by fmetze** [comment]
How big is the ACLEW starter database that we would being in here?

I think we want two things:

1) one file which we could use for simple testing (and one should be able to eye the result and see that it is reasonable)
2) an easy way to bring in an entire set of files for testing and scoring

**Comment by jukaradayi** [comment]
If I try to download all the files (wether I'm logged or not, it's the same), I can only get these ones: 

Files that are in pair:
  BER_0713_07_02_21041-CP.eaf  
  BER_0713_07_02_21041.wav  

  BER_0485_12_07_09123-CP.eaf  
  BER_0485_12_07_09123.wav  

  ROS_5271_20_01_03600-CA.eaf  
  ROS_5271_19_01_3600.wav

  BER_2224_16_11_01293-CP.eaf  
  BER_2224_01_11_01293.wav  

Files that are alone:
  wavs:
    ROW_3628_18_03_10108.wav  
    ROW_2811_11_01_18780.wav  
    ROW_0049_24_05_13543.wav  

  eafs:
    SOD_9733_08_01_36000-JB.eaf  
    SOD_5223_11_03_34509-JD.eaf  
    SOD_8560_10_01_30182-JK.eaf
    WAR_9755_03_01_30816-MM.eaf  
    WAR_2337_06_02_03094-JB.eaf  
    WAR_5959_09_01_00857-CP.eaf  

When I access the https://nyu.databrary.org/volume/390 webpage, I can indeed see that the missing files have a small lock icon next to them in the name column. So, should we only include the 4 files that have both wav and eaf for now ?

**Comment by fmetze** [comment]
4 files should be enough for a functional test for now, right? 4 is more than 1, which is the main purpose of this.

**Comment by alecristia** [comment]
Yes, considering only on the fully public files is the best solution. Having mismatched files could be part of the test.

By "include" you mean consider in the test, right? We are still having the vagrant wget the files? As I mentioned in our meeting (and now I state it publicly), I think it would be desirable that this ACLEW tool makes reference to ACLEW data, which also helps users gain familiarity with e.g. the annotation structure used (as well as sharing via databrary).
