### ISSUE TITLE
To-Combo-Sad fails when input wav are in stereo

### ISSUE THREAD

**Issue by jukaradayi** [srvk/DiViMe#25]
When trying to run the To-Combo-Sad tool on stereo wav files, the tool fails and gives no output. 
One possible fix could be to add in the tool wrapper a section that checks if the wav file has more than one channel, and in that case uses SoX to convert it to a temp wav file with 1 channel.

**Comment by riebling** [comment]
Good idea. I wonder if there's a more general approach to ensure that input data formats are all first normalized to monaural WAV. But it doesn't hurt to have individual tools do some format checking as well. Guarding against ALL input formats might get tricky, for example sometimes SoX sometimes refuses to convert MP3. I think we're OK because we install `libsox-fmt-all`

**Comment by jukaradayi** [comment]
Do the other tools also have trouble whith non monaural WAV ? I remember that noiseme works differently but still works no ? I never compared the actual results when running on stereo vs mono, it might be interesting to see if the tools behave the same or not.

But that's a good point. I implemented (in github.com/srvk/tools/tocombo_sad.sh) a first fix that checks if it has more than 1 channel, and if so, create a temp wav file with 1 channel. If needed we could externalise in a small script this check and advise people to run it when starting the VM to "clean" their data (it might sound a bit scary...). And with this we could add a complete input formats check (mp3 as you said etc..).

**Comment by jukaradayi** [comment]
Closing the issue since the problem for TocomboSad is fixed - We should keep in mind what you said though, about ensuring normalized monaural WAV in the beginning !
