### ISSUE TITLE
Adapt the OpenSmile SAD into our pipeline

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#3]
Write wrappers so that it works the same as the other tools (see sample instructions below). This entails:

- [ ] accept WAV input
- [ ] produce RTTM output
- [ ] use standard locations / temp folders

# Target instructions #
For the SAD tools, type a command like the one below, being careful to type the SAD tool name instead of SADTOOLNAME:

`$ vagrant ssh -c "tools/SADTOOLNAME.sh data/"`

The SAD options are:
- SADTOOLNAME = ldc_sad
- SADTOOLNAME = noisemes_sad
- SADTOOLNAME = noisemes_full

This will create a set of new rttm files, with the name of the tool added at the beginning. For example, imagine you have a file called participant23.wav, and you decide to run both the LDC_SAD and the Noisemes analyses. You will run the following commands:

```
$ vagrant ssh -c "tools/ldc_sad.sh data/"
$ vagrant ssh -c "tools/noisemes_sad.sh data/"
```

And this will result in your having the following three files in your /data/ folder:

- participant23.wav
- ldc_sad_participant23.rttm
- noisemes_sad_participant23.rttm

If you look inside one of these .rttm's, say the ldc_sad one, it will look as follows:

```
SPEAKER	participant23	1	0.00	0.77	<NA>	<NA>	speech	<NA>
SPEAKER	participant23	1	0.77	0.61	<NA>	<NA>	nonspeech	<NA>
SPEAKER	participant23	1	1.38	2.14	<NA>	<NA>	speech	<NA>
SPEAKER	participant23	1	3.52	0.82	<NA>	<NA>	nonspeech	<NA>
```

This means that LDC_SAD considered that the first 770 milliseconds of the audio were speech; followed by 610 milliseconds of non-speech, followed by 2.14 seconds of speech; etc.

**Comment by riebling** [comment]
I know we were asked to not redistribute or use ldc_sad_hmm. We can make some progress on it by using cached code. Is there a way to check with Neville on the status/availability of an open source release?

**Comment by riebling** [comment]
https://github.com/srvk/tools/blob/master/opensmile_sad.sh 
(do we need to update documentation to  include this script?)

**Comment by riebling** [comment]
Let's update opensmileSad to use OpenSMILE v2.3.0 - then we can eliminate the old 2.1.0 version from the system. The SMILExtract binary can be used system wide, still. However the scripts to perform SAD (or VAD, as OpenSMILE calls it) need to be ported to use slightly different settings.

If we can get the configurations ported to work the slightly different way that OpenSMILE 2.3.0 requires, we can eliminate installing 2 versions of OpenSMILE.

Also, the way we use it to do SAD has a bug, of sorts: in the ultimate working directory used by OpenSMILE SAD, it creates and leaves behind lots of WAV files, one for each utterance. it would be great to not actually write these out.  

There seem to be 2 ways of running VAD (as they call it), one of them produces CSV. Currently our wrapper runs it the other way, and maybe, probably shouldn't. I'm thinking Zixing might be best to work this out, having possibly the most OpenSMILE expertise among us. :)

In the process of doing this, since OpenSMILE is a 'commercial tool' with a code base we don't control, it makes sense to put our customizations somewhere *other* than the tool home folder. Specifically, the modifications we make to the VAD configuration file for OpenSmile should go in conf/ (/vagrant/conf/) - and because they import other configuration files, those should go in conf/ as well.

**Comment by riebling** [comment]
@MarvinLavechin - could you look at the new configs in /vagrant/conf/ for OpenSMILE VAD to help redo the fix to prevent the writing of WAV files  in `/home/vagrant/repos/opensmile-2.3.0/scripts/vad`? (the working directory of OpenSMILE VAD) I could not quite figure it out. :)
https://github.com/srvk/DiViMe/blob/major_reorganization/conf/vad_segmenter_aclew.conf

I was only able to get opensmileSad to work with 2.3.0 without crashes, config errors, component errors, etc. by building upon the example vad config files, rather than working backwards from our modified ones.

**Comment by junghanw** [comment]
@riebling opensmile-2.3.0 seems to fail in test.sh 
```
Testing OpenSmile SAD...
Processing BN32_010007_test ...
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: /home/vagrant/utils/vad_segmenter_aclew.conf.txt
(MSG) [2] in cComponentManager : successfully registered 96 component types.
(WARN) [1] in instance 'turn' : readVad=1, and threshold2 set to a value which looks like log- or rms-energy thresholds! You should remove the threshold option, or consider that you are settingthe VAD threshold with it!
(WARN) [1] in instance 'turn' : readVad=1, and threshold set to a value which looks like log- orrms-energy thresholds! You should remove the threshold option, or consider that you are setting the VAD threshold with it!
(MSG) [2] in instance 'csvSink' : No filename given, disabling this sink component.
(ERROR) [1] in dataMemory : level 'frames' was not found! component 'waveSinkCut.reader' requires it for reading.
     it seems that no dataWriter has registered this level! check your config!
(ERROR) [1] in dataMemory : there were unresolved read-requests, please check your config file for missing components /  missing dataWriters or incorrect level names (typos, etc.) !
terminate called after throwing an instance of 'cComponentException'
/home/vagrant/launcher/opensmileSad.sh: line 43: 23035 Aborted                 (core dumped) LD_LIBRARY_PATH=/usr/local/lib $OPENSMILE -C $CONFIG_FILE -I $file -turndebug 1 -saveSegmentTimes $workdir/${id}.txt -logfile $workdir/opensmile-vad.log
ls: cannot access /vagrant/data/VanDam-Daylong/BN32/opensmile-test/temp/opensmileSad/*.txt: No such file or directory
   OpenSmile SAD failed - no RTTM output
```

**Comment by riebling** [comment]
Seems to be working now on a fresh clone of major_reorganization branch, so closing. (probably caught a partially complete commit of the 2.3.0 OpenSmile version upgrade)
