### ISSUE TITLE
change default SAD when running diarization from ldc_sad to noisemes

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#34]
ldc_sad is still not publicly available so it would be safer for the SAD default to be noisemes

Please change this in:

- [x]  tools/diartk.sh
- [x]  tools/yunitate.sh

**Comment by alecristia** [comment]
Eric, I assigned this to you only because we were having this parallel discussion about how yunitate.sh should work. Let me know if the issue isn't clear! (Julien already did the diartk change.)

**Comment by riebling** [comment]
I will ask a question, just to get more clarity.

For tools/yunitate.sh, because Yunitator provides it's own SAD as well as diarization, there is no argument to the script for 'which SAD to perform'.  (also, it's a little bit confusing that the usage message for diartk.sh refers to the input SAD as "transcription", maybe that can be a new minor issue)

So probably this is meant to apply to the YuniSegs script that takes as input RTTM.

But there's yet another level of complexity here, because that script assumes RTTM has been already computed in a workflow that consists of 2 steps:  1. compute SAD  2. perform diarization.  But now inspecting tools/diartk.sh it seems that the 'compute sad' is baked into the run script, including that every diarization tool has scripted code in it to run EVERY possible SAD tool (and if new SAD tools are added, each and every diarization script will need to be modified)

I guess by separating in stages, that might reduce duplication of code, and I just wasn't paying attention to the design where SAD is 'baked into' all the diarization run scripts. Now I know! :)

The more useful way of running Yunitator would be YuniSegs, where it CAN accept input that has SAD. Except I'll have to follow the pattern of code in diartk.sh so that it doesn't just accept SAD as input, but actually PERFORMS the SAD as well.

**Comment by riebling** [comment]
Nope I'm still wrong. diartk.sh doesn't PERFORM SAD, it just POINTS TO various flavours of SAD that have been given special names (we hope!)

SO the real purpose of assigning me this is to establish that we need a way of running Yunitator in the way that diartk is run, whereby the SAD is chosen based on a keyword baked into the SAD files, then USE THAT as the input SAD, using the special name, e.g. tocombo_sad_XXXX.rttm or opensmile_sad_XXXX.rtm, etc.  Got it!

**Comment by riebling** [comment]
Going through the exercise of working on this gives an idea: a general script in tools/ that knows how to iterate over an input folder of audio files. You give it the name of a SAD tool, and the name of a Diarization tool, and it takes care of everything. It could even be clever in that if the same SAD already exists (was computed before) does not re-run, but rather re-uses that SAD.

This seems like it would help generalize the case for a "run script to rule them all" :)

**Comment by riebling** [comment]
Hm it seems like for tools/diartk.sh it will never default to anything for SAD. If you fail to supply the name of a SAD tool, it exits with usage instructions, because there were too few arguments, rather than proceed and use a default empty case SAD (noisemes)

**Comment by alecristia** [comment]
Thanks for the sleuthing! Sounds like diartk wasn't in fact programmed how I thought. Here's the relevant section of the usage instructions:

> 5. For the diarization tools, type a command like the one below, being careful to type the diarization tool name instead of DiarTOOLNAME:
> 
> `$ vagrant ssh -c "tools/DiarTOOLNAME.sh data/ noisemes"`
> 
> The DiarTOOLNAME options are:
> - DiarTOOLNAME = diartk
> - DiarTOOLNAME = yunitate
> 
> Notice there is one more parameter provided to the system in the call; in the example above "noisemes". This is because the DiarTK tool only does talker diarization (i.e., who speaks) but not speech activity detection (when is someone speaking). Therefore, this system requires some form of SAD. With this last parameter, you are telling the system which annotation to use. At present, you can choose between:
> 
> - ldc_sad: this means you want the system to use the output of the LDC_SAD system. If you have not run LDC_SAD, the system will run it for you.
> - noisemes: this means you want the system to use the output of the noisemes system. If you have not run LDC_SAD, the system will run it for you.
> - opensmile: this means you want the system to use the output of the opensmile system. If you have not run opensmile, the system will run it for you.
> - tocombosad: this means you want the system to use the output of the tocombo_sad system. If you have not ran tocombosad, the system will run it for you.
> - textgrid: this means you want the system to use your textgrid annotations. Notice that all tiers count, so if you have some tiers that are non-speech, you should remove them from your textgrids before you start. Please note that the system will convert your textgrids into .rttm in the process.
> - eaf: this means you want the system to use your eaf annotations. Notice that all tiers count, so if you have some tiers that are non-speech, you should remove them from your eaf files before you start. Please note that the system will convert your eafs into .rttm in the process.
> - rttm: this means you want the system to use your rttm annotations. Notice that all annotations that say "speech" in the eigth column count as such. 
> 
> 
> Finally, if no parameter is provided, the system will default to noisemes.
> 

Your comment raises another point: We have not been careful in our naming conventions. Notice the instructions referring to noisemes (should be noisemesSad?) and yunitate (you call it yuniSegs). 

In any case, sounds like you're on this. I'll leave slack open if you want to discuss a course of action.

**Comment by riebling** [comment]
This is good information. At least looking at diartk.sh, it looks like it does not "run SAD for you". The script looks for pre-existing SAD RTTMs with a first naming convention (lowercase) of tool that created them, then produces output with a DIFFERENT naming convention (camel case) in tuples like:
```
  * ldc_sad   : ldc_sad_XXX.rttm     : diartk_ldcSad_XXX.rttm
  * noisemes  : noisemes_sad_XXX.rtm : diartk_noisemesSad_XXX.rttm
  * tocombosad: tocombo_sad_XXX.rtm  : diartk_tocomboSad_XXX.rttm
  * opensmile : opensmile_sad_XXX.rtm: diartk_opensmileSad_XXX.rttm
  * textgrid  : XXX.TextGrid         : diartk_goldSad_XXX.rttm
  * eaf       : XXX.eaf              : diartk_goldSad_XXX.rttm
  * rttm      : XXX.rttm             : diartk_goldSad_XXX.rttm
```
yuniSegs is a new and different way of running yunitate, so it has a new name. I did not want to change the way it works while keeping the same name. So yunitate.sh still works as it did before (except for accepting SAD input, of course, since it produces it's own!).  Every time we add a new SAD tool, we may have to update, adding it to each and every Diarization tool run script.  That's why my vision for "one script to rule them all" - even if it work slightly different than the way the instructions say - might help development moving forward.

Would it be possible to present more clearly examples of how to run without introducing the abstraction "diarTOOLNAME"?  If we only have 2 possible tools,  I feel these instructions would be more clear:

5. There are currently 2 diarization tools: `diartk` and `yuniSeg`. Examples of running each (with noisemes as their SAD input, explained below) are:
```$ vagrant ssh -c "tools/diartk.sh data/ noisemes"```
```$ vagrant ssh -c "tools/yuniSeg.sh data/ noisemes"```

Of course it would be even more clear to explain the SAD argument first :) but I really think we could do without "diarTOOLNAME"

**Comment by alecristia** [comment]
That sounds good to me! Would you like to edit directly
(docs/source/usage.md) or shall I?

**Comment by riebling** [comment]
This makes me so happy, I will edit right away. :)

**Comment by alecristia** [comment]
- [ ] remove SADTOOLNAME periphrasis
- [ ] remove language suggesting that tool runs SAD for you
