### ISSUE TITLE
yuniSeg takes gold rttm instead of the predicted ones

### ISSUE THREAD

**Issue by MarvinLavechin** [srvk/DiViMe#70]
While running : 

`tools/yuniSeg.sh data/yuni noisemes`

With **data/yuni** containing **test2.wav** and **noisemes_sad_test2.rttm** (without the gold rttm), I noticed that the script was giving the following error : 

`./runYuniSegs.sh: line 95: /vagrant/data/yuni/test2.rttm: No such file or directory`

Indeed, if the gold rttm is here, runYuniSegs takes it as the reference file (even if noisemes is given as an argument).

There are some troubles around the naming convention visibly.

**Comment by MarvinLavechin** [comment]
That was the case regardless the model that was used.

I fixed the bug by giving the right model_prefix for each system. It's due to the model naming convention which is not consistent with the output files.

**Comment by riebling** [comment]
oh my, yes, this might have been my failure to code for the way tools/yuniSeg.sh gets it's segmentation input from RTTM. I assumed it only gets segmentation from filenames that match the input, indeed as you observed, rather than use indirection based on another argument that specifies a component of the filename from which to base the source of segmentation input - that segments may come from more than one SAD tool, and that we bake SAD tool names into the RTTM :)
Good catch!
