### ISSUE TITLE
data folder not visible from within machine

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#75]
I've made minor changes to the vagrantfile and re-built, but now vagrant no longer sees the data folder. I'm pretty sure I didn't change anything in the vagrantfile (which in any case makes no reference to data) -- so where did I go wrong? (If you want to see a list of changes: https://github.com/srvk/DiViMe/commit/64640be6e7904b5f15c1e8bb9e9e502575e1faf2#diff-23b6f443c01ea2efcb4f36eedfea9089)

**Comment by junghanw** [comment]
You mean you can't get access to /vagrant/data directory?

**Comment by alecristia** [comment]
got it - there is /home/vagrant, and /vagrant -- and these are not the same.

data is in /vagrant, whereas e.g. anaconda is in /home/vagrant.

This is confusing, don't you think?

**Comment by riebling** [comment]
Agree (never mind my slack response... stale message!) - the unfortunate side effect that the default username, and therefore home folder in Vagrant VMs is `vagrant` and `/home/vagrant` - but I would worry if we try and change (for clarity's sake) the naming of `/vagrant` to anything else because SO MANY scripts rely on it now as the place where the VM accesses the shared host folder to get to `data/`

**Comment by alecristia** [comment]
incorporated all arguments and ideas to a document in progress explaining the vm structure
