### ISSUE TITLE
consider creating procedure for tool submission as a package

### ISSUE THREAD

**Issue by edupoux** [srvk/DiViMe#80]
(and/or create tools to verify/check that a new tool submission contains all the required bits and pieces)

**Comment by alecristia** [comment]
The idea would be, instead of having tool producers modify things in launcher, docs, and bootstrap.sh, they should submit a set of files that gets evaluated and sorted into these three locations.

Upon further discussion, we decide there is no clear advantage for one over the other solution. I'm therefore closing this issue.
