### ISSUE TITLE
readthedocs does not reflect 1.1's docs

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#98]
The latest release (1.1) has an improved documentation, yet divime.readthedocs.io has the old, messy one. What is the procedure for getting changes reflected?

**Comment by alecristia** [comment]
in fact, the master branch doesn't have the improved docs -- did this section not merge? Or was the release not based on master?

**Comment by riebling** [comment]
I have no idea. I really am not the best person for doing commits or merges or rebases or branches or any of the other git verb vocabulary. But I can at least guess, and try:

I didn't do anything to the master branch. We did a lot of development in major_reorganization. Jaden merged most all of that into yunified. (techically origin/yunified, for naming convention reasons I do not understand, probably some git special state).   Then I cleared and fixed conflicts and code and tests and launcher scripts so things all passed the test, and looked good to me, and made this be release 1.1.

I did not do anything to change the content of head, or mark a different branch as being the default branch.

Since then, to try and resolve this issue, I:

 * Merged major_reorganization into master branch.  (I think... I don't know, this is my first time doing this, and I am no Git expert, and may well have done several things wrong)
 * Merged yunified into master branch. (this involved editing almost every file that changed, to "resolve conflicts" apparently means you have to hack source files and look at every single change)

Now we have a master branch that might reflect release 2.0. but I have no confidence because it has not been tested. So it's still technically broken, until being tested, and having everyone look at it and make sure their changes are there, and that artifacts like documentation are just as up to date.

I'm not sure what the procedure is for updating divime.readthedocs.io. Assuming we need to create one. Maybe it's even documented somewhere, for developers: "how to update divime.readthedocs.io". Or could be.

**Comment by riebling** [comment]
https://github.com/srvk/DiViMe/wiki/gitProblems

**Comment by alecristia** [comment]
readthedocs fixed by the merge
